import Head from "next/head";
import ButtonPrimary from "../components/ButtonPrimary";
import ButtonSecondary from "../components/ButtonSecondary";
import ContactFooter from "../components/ContactFooter";
import Footer from "../components/Footer";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Minimalist Portfolio Website</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='theme-color' content='#fafafa' />
        <link rel='icon' href='/favicon-32x32.png' />
      </Head>

      <Header />

      <main className='mt-[104px] bg-secondary_grey_bg px-8 sm:mt-[144px] sm:px-10'>
        <img
          src='/homepage/mobile/image-homepage-hero@2x.jpg'
          alt=''
          className='mb-6 sm:hidden'
        />
        <div className='relative h-auto w-auto'>
          <img
            src='/homepage/tablet/image-homepage-hero@2x.jpg'
            alt=''
            className='mb-6 hidden sm:mb-0 sm:inline-block'
          />
          <div className='sm:absolute sm:bottom-0 sm:flex sm:h-[278px] sm:w-[514px] sm:flex-col sm:justify-end sm:bg-secondary_grey_bg'>
            <h2 className='mb-8 sm:w-[458px]'>
              Hey, I'm Alex Spencer and I love building beautiful websites
            </h2>
            <ButtonPrimary href='#about-me-section'>ABOUT ME</ButtonPrimary>
          </div>
        </div>

        <div className='mb-8 mt-24 sm:mb-0 sm:grid sm:grid-cols-10'>
          <img
            src='/homepage/mobile/image-homepage-profile@2x.jpg'
            alt=''
            className='sm:hidden'
          />
          <img
            src='/homepage/tablet/image-homepage-profile@2x.jpg'
            alt=''
            className=' hidden sm:col-span-4 sm:inline-block'
          />
          <div className='sm:col-span-6 sm:flex sm:flex-col sm:justify-between sm:pl-[68px]'>
            <div>
              <hr />
              <div id='about-me-section'>
                <h2 className='mb-7 mt-8'>About Me</h2>
                <p className='mb-6'>
                  I'm a junior front-end developer looking for a new role in an
                  exciting company. I focus on writing accessible HTML, using
                  modern CSS practices and writing clean JavaScript. When
                  writing JavaScript code, I mostly use React, but I can adapt
                  to whatever tools are required. I'm based in London, UK, but
                  I'm happy working remotely and have experience in remote
                  teams. When I'm not coding, you'll find me outdoors. I love
                  being out in nature whether that's going for a walk, run or
                  cycling. I'd love you to check out my work.
                </p>

                <ButtonSecondary href='/portfolio'>
                  GO TO PORTFOLIO
                </ButtonSecondary>
              </div>
            </div>
            <hr className='hidden sm:inline-block' />
          </div>
        </div>

        <hr className='mt-[50px] mb-[35px] sm:hidden' />

        <ContactFooter />
      </main>

      <Footer />
    </div>
  );
}
